version: '3.8'

services:
  pihole:
    image: pihole/pihole:2024.01.0
    container_name: pihole
    environment:
      TZ: "Europe/Paris"
      WEBPASSWORD: "qwertyUwU"
      IPv6: "false"
      DNS1: '8.8.8.8'
    ports:
      #- "53:53/tcp"
      #- "53:53/udp"
      - "8081:80/tcp"
    volumes:
      - "./tmp_utils_fuckeries/etc-pihole:/etc/pihole"
      - ".tmp_utils_fuckeries/etc-dnsmasq.d:/etc/dnsmasq.d"
    mac_address: 02:42:ac:14:00:32
    restart: unless-stopped
    networks:
      net1:
       ipv4_address: 172.20.0.50

  attacker:
    tty: true
    build: ./attacker
    container_name: attacker
    networks:
      net1:
        ipv4_address: 172.20.0.2 
    dns:
      - 172.20.0.50 # Pi-hole IP

  snort_box:
    build: ./snort_box
    container_name: snort
    networks:
      net1:
        ipv4_address: 172.20.0.3 
    cap_add:
      - NET_RAW 
      - NET_ADMIN
    privileged: true

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
    - "8080:80"
    mac_address: 02:42:ac:14:00:04
    networks:
      net1:
        ipv4_address: 172.20.0.4 
    ulimits:
      nofile:
        soft: 1000
        hard: 1000
    dns:
      - 172.20.0.50 # Pi-hole IP


  user:
    tty: true
    build: ./user
    container_name: user
    networks:
      net1:
        ipv4_address: 172.20.0.5
    dns:
      - 172.20.0.50

networks:
  net1:
    ipam:
     config:
       - subnet: 172.20.0.0/24
