version: '3.8'

services:
  pihole:
    image: pihole/pihole:latest
    environment:
      WEBPASSWORD: "qwertyUwU"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp"
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d"
    restart: unless-stopped
    networks:
      default:
       ipv4_address: 172.20.0.50

  attacker:
    build: ./attacker
    networks:
      default:
        ipv4_address: 172.20.0.2 
    dns:
      - 172.20.0.50 # Pi-hole IP

  snort_box:
    build: ./snort_box
    networks:
      default:
        ipv4_address: 172.20.0.3 

  nginx:
    build: ./nginx
    ports:
    - "8080:80"
    networks:
      default:
        ipv4_address: 172.20.0.4 

  user:
    build: ./user
    networks:
      - default
    dns:
      - 172.20.0.50

networks:
  default:
    ipam:
     config:
       - subnet: 172.20.0.0/24
