# Utiliser l'image officielle de Nginx avec la version 1.18
FROM nginx:1.20

# Copier le fichier de configuration personnalisé dans le conteneur
COPY nginx.conf /etc/nginx/nginx.conf

# Exposer le port 80 pour les connexions HTTP
EXPOSE 80